services:
  db:
    container_name: db
    build:
      context: .
      dockerfile: Dockerfile.db
      target: db
    image: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    restart: unless-stopped

  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile.api
    image: api
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: root
      DB_NAME: test_db
    volumes:
      - .:/app
      - /app/node_modules 
    restart: unless-stopped
